### ISSUE TITLE
using bootstrap less in custom files? 

### ISSUE THREAD

**Issue by reluem** [heimrichhannot/contao-bootstrapper#2]
for some reason, I cannot use the Bootstrap mixins/variables in a custom less file in my extasset CSS group.

mixins like `.make-xs-column(12);` are not handled at all.
including Bootstrap variables such as `.panel` in my own class throws errors in the frontend, that this class `.panel` is not defined.
-> thus I figured that referencing Bootstrap is only possible inside the group variables file, which worked.
This is probably not the intended behavior, right?

also, when I try to integrate e.g. the `slick-theme.less` in the css group, the less parser causes timeouts, while with the normal contao parser everything works fine!
> [21-Jul-2017 16:45:30 Europe/Berlin] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /is/htdocs/xxx/www/xx/vendor/oyejorge/less.php/lib/Less/Tree/Dimension.php on line 32

Using the bootstrap/slick less files with contao itself works totally fine.
Are there plans in the future to split this extension from extassets? this has never properly/satisfyingly worked in my environment, but I'd love to use the functionality of `contao-bootstrapper`

**Comment by fatcrobat** [comment]
As you already noticed, the php less parser is not very high performance. We always notice the high memory usage, and for the most of our clients production environments the memory is locked at less than 96 MB. For the bootstrap framework for example, the less memory consumption is quite big. For this reason it is not possible to provide more than the variables.less within `$GLOBALS['TL_USER_CSS']`.

Bootstrap 4 will be only available in scss (Sass) and all less files are gone. We do not support extassets any longer for Contao 4 as the memory consumption of any css preprocessor like sass or less is not practicable on production environment and shared hosts. 

For contao 4 with bootstrap 4 and scss you can have an eye on our new extension (Contao Stylesheet Manager - https://github.com/heimrichhannot/contao-stylesheet-manager-bundle). SCSS/LESS generation should be done locally and deployed on production as pure css.

`contao-bootstrapper` in version 2 does currently only support bootstrap 4 and does no longer require `contao-extassets`

**Comment by reluem** [comment]
thanks for clarification, will take a look at v2 or the stylesheet manager then!
